// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"yolo-team/yolo-cli/internal/model"

	"gorm.io/cli/gorm/field"
)

var Document = struct {
	ID        field.Number[int64]
	Key       field.String
	ProjectID field.Number[int64]
	Title     field.String
	Creator   field.String
	SortOrder field.Number[int]
	CreatedAt field.Time
	UpdatedAt field.Time
	Project   field.Struct[model.Project]
}{
	ID:        field.Number[int64]{}.WithColumn("id"),
	Key:       field.String{}.WithColumn("key"),
	ProjectID: field.Number[int64]{}.WithColumn("project_id"),
	Title:     field.String{}.WithColumn("title"),
	Creator:   field.String{}.WithColumn("creator"),
	SortOrder: field.Number[int]{}.WithColumn("sort_order"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	Project:   field.Struct[model.Project]{}.WithName("Project"),
}
