// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var Executor = struct {
	ID        field.Number[int64]
	Name      field.String
	Role      field.String
	Soul      field.String
	CreatedAt field.Time
	UpdatedAt field.Time
}{
	ID:        field.Number[int64]{}.WithColumn("id"),
	Name:      field.String{}.WithColumn("name"),
	Role:      field.String{}.WithColumn("role"),
	Soul:      field.String{}.WithColumn("soul"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
}
