// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"yolo-team/yolo-cli/internal/model"

	"gorm.io/cli/gorm/field"
)

var Issue = struct {
	ID          field.Number[int64]
	Key         field.String
	ProjectID   field.Number[int64]
	Status      field.String
	Title       field.String
	Description field.String
	Deadline    field.Time
	Priority    field.String
	ExecutorID  field.Number[int64]
	RepoURL     field.String
	RepoName    field.String
	BranchName  field.String
	SortOrder   field.Number[int]
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Project     field.Struct[model.Project]
	Executor    field.Struct[model.Executor]
	Documents   field.Slice[model.Document]
}{
	ID:          field.Number[int64]{}.WithColumn("id"),
	Key:         field.String{}.WithColumn("key"),
	ProjectID:   field.Number[int64]{}.WithColumn("project_id"),
	Status:      field.String{}.WithColumn("status"),
	Title:       field.String{}.WithColumn("title"),
	Description: field.String{}.WithColumn("description"),
	Deadline:    field.Time{}.WithColumn("deadline"),
	Priority:    field.String{}.WithColumn("priority"),
	ExecutorID:  field.Number[int64]{}.WithColumn("executor_id"),
	RepoURL:     field.String{}.WithColumn("repo_url"),
	RepoName:    field.String{}.WithColumn("repo_name"),
	BranchName:  field.String{}.WithColumn("branch_name"),
	SortOrder:   field.Number[int]{}.WithColumn("sort_order"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
	Project:     field.Struct[model.Project]{}.WithName("Project"),
	Executor:    field.Struct[model.Executor]{}.WithName("Executor"),
	Documents:   field.Slice[model.Document]{}.WithName("Documents"),
}

var UpdateIssueRequest = struct {
	Title       field.String
	Description field.String
	Status      field.String
	Priority    field.String
	ExecutorID  field.Number[int64]
	Deadline    field.Time
	RepoURL     field.String
	RepoName    field.String
	BranchName  field.String
}{
	Title:       field.String{}.WithColumn("title"),
	Description: field.String{}.WithColumn("description"),
	Status:      field.String{}.WithColumn("status"),
	Priority:    field.String{}.WithColumn("priority"),
	ExecutorID:  field.Number[int64]{}.WithColumn("executor_id"),
	Deadline:    field.Time{}.WithColumn("deadline"),
	RepoURL:     field.String{}.WithColumn("repo_url"),
	RepoName:    field.String{}.WithColumn("repo_name"),
	BranchName:  field.String{}.WithColumn("branch_name"),
}
