// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var Project = struct {
	ID          field.Number[int64]
	Key         field.String
	Name        field.String
	Description field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
}{
	ID:          field.Number[int64]{}.WithColumn("id"),
	Key:         field.String{}.WithColumn("key"),
	Name:        field.String{}.WithColumn("name"),
	Description: field.String{}.WithColumn("description"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
}
