// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"gorm.io/cli/gorm/field"
)

var Task = struct {
	ID          field.Number[int64]
	Key         field.String
	IssueID     field.Number[int64]
	Title       field.String
	Description field.String
	Status      field.String
	SortOrder   field.Number[int]
	CreatedAt   field.Time
	UpdatedAt   field.Time
}{
	ID:          field.Number[int64]{}.WithColumn("id"),
	Key:         field.String{}.WithColumn("key"),
	IssueID:     field.Number[int64]{}.WithColumn("issue_id"),
	Title:       field.String{}.WithColumn("title"),
	Description: field.String{}.WithColumn("description"),
	Status:      field.String{}.WithColumn("status"),
	SortOrder:   field.Number[int]{}.WithColumn("sort_order"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
	UpdatedAt:   field.Time{}.WithColumn("updated_at"),
}
